//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRCStok
{
    using System;
    using System.Collections.Generic;
    
    public partial class AylikRapor
    {
        public long AylikRaporId { get; set; }
        public string GidenUrunler { get; set; }
        public string GidenMusteriler { get; set; }
        public string UrunGramaji { get; set; }
        public string UrunPaketi { get; set; }
        public string Tarih { get; set; }
        public string Ay { get; set; }
        public string Fiyati { get; set; }
        public string FaturaDurumu { get; set; }
    }
}
