//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRCStok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uretim
    {
        public long UretimId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunAdedi { get; set; }
        public string UrunAmbalaji { get; set; }
        public string UrunGramaji { get; set; }
        public string UrunUretimTarihi { get; set; }
        public string Gun { get; set; }
        public string Ay { get; set; }
        public string Yil { get; set; }
        public string Uretici { get; set; }
        public string UreticiFaturasi { get; set; }
    }
}
