//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRCStok
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunSepeti
    {
        public long UrunSepetiId { get; set; }
        public string MusteriAdi { get; set; }
        public string UrunAdi { get; set; }
        public string UrunAdedi { get; set; }
        public string UrunGramaji { get; set; }
        public string UrunAmbalaji { get; set; }
        public string UrunFiyati { get; set; }
        public string UrunFaturasi { get; set; }
        public string Tarih { get; set; }
        public string Ay { get; set; }
        public string Yil { get; set; }
        public string Gun { get; set; }
    }
}
