//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRCStok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public long UrunlerId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunFiyati { get; set; }
        public string UrunAdedi { get; set; }
        public string UrunGramaji { get; set; }
        public string UrunPaketi { get; set; }
        public string UrunBarkodu { get; set; }
        public string UrunEklemeTarihi { get; set; }
    }
}
